#!bin/bash

apt-get update;
apt-get install -y libgl1-mesa-dev;
apt-get install -y libglu1-mesa-dev;
apt-get install -y libdevil-dev;
apt-get install -y libx11-dev;
apt-get install -y libpthread-stubs0-dev;
apt-get install -y libxxf86vm-dev;
apt-get install -y libxrandr-dev;
apt-get install -y libglfw-dev;
apt-get install -y libaudiere-dev;
apt-get install -y libfreetype6-dev
